FROM pytorch/pytorch:2.0.0-cuda11.7-cudnn8-devel

RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get install -y \
    sudo 

ENV TZ=Europe/London

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# RUN useradd -ms /bin/bash user && \
#     usermod -aG sudo user

# RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# USER user

WORKDIR /root

ENV DEBIAN_FRONTEND=noninteractive

RUN sudo apt -y install --no-install-recommends \
    automake \
    build-essential \
    cmake \
    curl \
    git \
    python3 \
    python3-dev \
    python3-pip \
    unzip \
    wget \
    zip \
    nano

RUN sudo apt-get clean

RUN conda init bash

RUN echo "export CUDA_HOME=/usr/local/cuda-11.7" >> /etc/bash.bashrc
 
ENV CUDA_HOME=/usr/local/cuda-11.7

RUN /opt/conda/bin/python3 -m pip install --upgrade pip

RUN curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash

RUN sudo apt-get install -y git-lfs

RUN python3 -m pip install poetry

WORKDIR /root

RUN git clone --depth 1 --branch v0.5.0 https://github.com/lava-nc/lava-dl.git

WORKDIR /root/lava-dl

RUN poetry export --without-hashes -f requirements.txt -o requirements.txt

RUN echo "lava-dl==0.5.0" >> requirements.txt

RUN python3 -m pip install -r requirements.txt

RUN python3 -m unittest

RUN git clone --depth 1 --branch v0.9.0 https://github.com/lava-nc/lava.git

WORKDIR /root/lava

RUN python3 -m unittest

RUN python3 -m pip install --no-cache-dir nni==2.7 tqdm "typeguard<3" filelock==3.10 jupyterlab notebook ipywidgets seaborn


WORKDIR /root
